export const SORRY_WORDS = [
'Oh no - a Nat 1! You lost this time but come back tomorrow and you may fight again!',
'That was like casting fireball in an elevator, you lost this time but there will be another battle here tomorrow, see you then?',
'Oh dear! You were backstabbed by that one, come back tomorrow after you have quaffed a healing potion!',
'[Sound of sad trombone...] You lost, but worry not! There will be another chance to vanquish this page tomorrow, see you then?',
'Uh oh, the DM did not like your character - you dead!! Come back tomorrow with a new character!',
'The DM split the party - that never works out, you lose! Come back tomorrow when you\'ve found your party!',
'Uh oh the DM\'s had a bad day! You were never going to win. Come back tomorrow, hopefully the DM will be kinder to you!',
'You got stomped on by Dundle\'s pet Tarrasque! Here, take this superior healing potion and come back for more tomorrow!',
'Oh dear, you rolled a 1 on your Dundle check. Come again tomorrow when the dice may be kinder!',
'Ah snap!  That was a hard one, but worry not, there are many more chances to level up. Come back tomorrow to try again!',
'You\'ve run out of inspiration and your bard is at the bar! Too bad, come back tomorrow for another try!',
'You were like a level 1 wizard out of spells in a bar brawl! Fear not, there will be another fight here tomorrow, bring your spellbook!',
'Oh, third death saving throw failed... Wait, the party cleric has Revivified you! Now you can come back tomorrow for more, huzzah! ',
'You slipped up there! Take 20d6 fall damage and come back tomorrow for another go after a long rest!',
'Looks like you\'ll need a long rest after that beating! Come back tomorrow once you are recovered!',
'That was harder than Orcus\' mace in the face! Worry not, you can rise up again tomorrow for another go!',
'Wait... did you just drink the red potion? Oh dear... Come back tomorrow once you have recovered!',
'Uh oh, your sword was cursed and attacked you instead of the Dundle BBEG. Come back tomorrow once you have a new one!',
'Dundle has beaten you today but dust yourself off, quaff a healing potion and come back tomorrow when you will be victorious!',
'Attacking a Dundle with a club? Mwa ha ha haaaa! Dundle has resistance to bludgeoning damage! Come back tomorrow with a sword',
'Elminster shakes his head in disappointment, as you fail his test. But not to worry, there is a retake tomorrow on offer!',
'Volo was hoping you would do better, but do not despair, he has invited you to try again tomorrow!',
'Xanathar just blasted you with his disintegration ray, you are a pile of dust. Try again tomorrow once you have reassembled!'
  ]